name: Create new library packages

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
      - name: Build app
        run: yarn && yarn build
        env:
          BUILD_CONCURRENCY: 5
